server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
#  mail:
#    host: ${SMTP_HOST}
#    port: ${SMTP_PORT}
#    username: ${SMTP_USERNAME}  # Replace with your Mailtrap username
#    password: ${SMTP_PASSWORD}  # Replace with your Mailtrap password
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          debug: true